language: ruby

before_script:
  - mysql -e 'create database nyu_rooms_test;'
  - bundle exec rake db:schema:load

rvm:
  - "1.9.3"
  - "2.0.0"

git:
  submodules: false

notifications:
  email:
    - barnaby.alter@nyu.edu