language: ruby

services:
  - elasticsearch

env:
  -ROOMS_DB_USER=root ROOMS_DB_DATABASE=nyu_rooms_test ROOMS_DB_HOST=localhost ROOMS_SECRET_TOKEN=dd6f1b6faf2511a744f3f08644e76edcb6be01d7019a6e62947e3a76a2c5f1ea7f3206af6bd0409ed222a56b2a53788da8de1d3528547889cc59c7dbc27f4503 ROOMS_COOKIE_DOMAIN=.local ROOMS_BONSAI_URL=http://localhost:9200 LOGIN_URL=https://dev.login.library.nyu.edu SSO_LOGOUT_PATH=/logout

before_script:
  - sleep 30
  - mysql -e 'create database nyu_rooms_test;'
  - bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake environment tire:import CLASS=Room FORCE=true
  - RAILS_ENV=test bundle exec rake environment tire:import CLASS=Reservation FORCE=true
  - sleep 30

rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.5
  - 2.3.1

notifications:
  email:
    - lib-webservices@nyu.edu

sudo: false
