# External config to match actions to sprite image names
sort_desc: "icons-famfamfam-arrow_down"
sort_asc: "icons-famfamfam-arrow_up"
info: "icons-famfamfam-information"
show: "icons-famfamfam-magnifier"
back: "icons-famfamfam-arrow_undo"
add: "icons-famfamfam-add"
edit: "icons-famfamfam-wrench"
destroy: "icons-famfamfam-cross"
date: "icons-famfamfam-date"
resend: "icons-famfamfam-email_go"
warning: "icons-famfamfam-error"
photo: "icons-famfamfam-photo"
